services:
 accountsdb:
  container_name: accountsdb
  ports:
   - 3308:3306

  environment:
   MYSQL_DATABASE: accountsdb

  extends:
   file: common-config.yml
   service: microservice-db-config


 loansdb:
  container_name: loansdb
  ports:
   - 3309:3306

  environment:
   MYSQL_DATABASE: loansdb

  extends:
   file: common-config.yml
   service: microservice-db-config


 cardsdb:
  container_name: cardsdb
  ports:
   - 3310:3306

  environment:
   MYSQL_DATABASE: cardsdb
  extends:
   file: common-config.yml
   service: microservice-db-config



 configserver:
  image: "aresopollon/configserver:s7"
  container_name: configserver-ms
  ports:
   - "8071:8071"

  healthcheck:
   test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
   interval: 10s
   timeout: 5s
   retries: 10
   start_period: 10s
  extends:
   file: common-config.yml
   service: microservice-base-config

 accounts:
  image: "aresopollon/accounts:s7"
  container_name: accounts-ms
  ports:
   - "8080:8080"
  depends_on:
   accountsdb:
    condition: service_healthy
  environment:
   SPRING_APPLICATION_NAME: "accounts"
   SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb" #ilk kısım burada oluşturduğumuz service adımızdır
  extends:
   file: common-config.yml
   service: microservice-configserver-config

 loans:
  image: "aresopollon/loans:s7"
  container_name: loans-ms
  ports:
   - "8090:8090"
  depends_on:
   loansdb:
    condition: service_healthy
  environment:
   SPRING_APPLICATION_NAME: "loans"
   SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
  extends:
   file: common-config.yml
   service: microservice-configserver-config

 cards:
  image: "aresopollon/cards:s7"
  container_name: cards-ms
  ports:
   - "9000:9000"
  depends_on:
   cardsdb:
    condition: service_healthy
  environment:
   SPRING_APPLICATION_NAME: "cards"
   SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
  extends:
   file: common-config.yml
   service: microservice-configserver-config

networks:
 agim:
  driver: "bridge"