spring:
  application:
    name: "configserver"
  profiles:
    # eğer file system veya classpath kullanılıyorsa active: native
   active : git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/y-eren/Algoritmalar-java.git"
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///C://Users//Dell//Desktop//JavaMicroservices//bolum6//bolum6-2-cloud-config//configserver//src//main//resources//config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          searchPaths: "config"
  rabbitmq:
      host: "localhost"
      port : 5672
      username : "guest"
      password : "guest"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "659ADDA858E22"
server:
  port: 8071

