spring:
  application:
    name: "configserver"
  profiles:
    # eğer file system veya classpath kullanılıyorsa active: native
   active : git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git"
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///C://Users//Dell//Desktop//JavaMicroservices//bolum6//bolum6-2-cloud-config//configserver//src//main//resources//config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "659ADDA858E22"
server:
  port: 8071

